language:
  - node_js
  - version: 8

cache:
  yarn: true

before_install:
  - nvm install --lts
  - nvm use 'lts/*'
  - npm i -g yarn
  - nvm --version
  - npm --version
  - node --version
  - yarn --version
  - yarn

script:
  - yarn lint
  - yarn nyc

after_success:
  - chmod 0755 /Users/travis/build/l3laze/vdf-parser/.nyc_output
  - yarn textcov
  - yarn codecov && yarn codacy
  - rm -rf ./coverage && rm -f ./coverage.lcov

notifications:
  email: false
